# -*- coding: utf-8 -*-
"""Mental_health_survey.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L86ZZvvIsHcj2sVFb3of8isH1ecbAFIl

# **Data Loading & Cleaning**
"""

#Import Libraries & Load Dataset

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')
sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams['figure.dpi'] = 120

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('survey.csv')

print(f"Shape: {df.shape}")
print("\n--- First 5 Rows ---")
display(df.head())
print("\n--- Column Data Types ---")
print(df.dtypes)

# Missing Value Analysis & Imputation ---

print("=== Missing Values Per Column ===")
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({'Missing Count': missing, 'Missing %': missing_pct})
print(missing_df[missing_df['Missing Count'] > 0].sort_values('Missing Count', ascending=False))

# Fill known nullable columns with mode (most frequent value)
cols_to_fill = ['work_interfere', 'self_employed']
for col in cols_to_fill:
    mode_val = df[col].mode()[0]
    df[col].fillna(mode_val, inplace=True)
    print(f"  ✔ '{col}' nulls filled with mode: '{mode_val}'")

# Drop rows where critical columns are still null
critical_cols = ['Age', 'Gender', 'Country', 'treatment']
df.dropna(subset=critical_cols, inplace=True)

print(f"\nRemaining nulls: {df.isnull().sum().sum()}")
print(f"Shape after handling nulls: {df.shape}")

# Clean Age & Normalize Gender ---

print(f"Age range before: {df['Age'].min()} – {df['Age'].max()}")
df = df[(df['Age'] >= 18) & (df['Age'] <= 75)].copy()

print(f"Age range after : {df['Age'].min()} – {df['Age'].max()}")
print(f"Rows remaining  : {len(df)}")

def normalize_gender(g):
    g = str(g).lower().strip()
    if any(x in g for x in [
        'female', 'woman', 'f', 'girl', 'femal',
        'cis f', 'cis female', 'femake', 'female (cis)', 'woman'
    ]):
        return 'Female'
    elif any(x in g for x in [
        'male', 'man', 'm', 'boy', 'cis m',
        'cis male', 'maile', 'mal', 'male (cis)', 'make'
    ]):
        return 'Male'
    else:
        return 'Other'

df['Gender'] = df['Gender'].apply(normalize_gender)

print("\n=== Gender Value Counts After Normalization ===")
print(df['Gender'].value_counts())

# Standardize Categorical Columns & Final Summary ---

cat_cols = df.select_dtypes(include='object').columns.tolist()
for col in cat_cols:
    df[col] = df[col].astype(str).str.strip()

for col in ['Country', 'state']:
    if col in df.columns:
        df[col] = df[col].str.title()

df.drop(columns=['Timestamp', 'comments'], inplace=True, errors='ignore')

print("=== Cleaned DataFrame Info ===")
df.info()

print("\n=== Descriptive Statistics ===")
display(df.describe(include='all').T)

# Save Cleaned Dataset ---

output_path = 'survey_cleaned.csv'
df.to_csv(output_path, index=False)

print(f"Cleaned dataset saved as '{output_path}'")
print(f"   Rows    : {df.shape[0]}")
print(f"   Columns : {df.shape[1]}")
print(f"\n   Columns saved: {df.columns.tolist()}")

"""# **Univariate Analysis.**"""

# Age Distribution & Gender Bar Chart ---

df = pd.read_csv('survey_cleaned.csv')

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.histplot(df['Age'], bins=20, kde=True, ax=axes[0],
             color='steelblue', edgecolor='white', linewidth=0.5)
axes[0].set_title('Age Distribution', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Age')
axes[0].set_ylabel('Count')
axes[0].axvline(df['Age'].median(), color='tomato', linestyle='--',
                linewidth=1.5, label=f"Median: {df['Age'].median():.0f}")
axes[0].legend()

gender_counts = df['Gender'].value_counts()
colors = ['#4C72B0', '#DD8452', '#55A868']
axes[1].bar(gender_counts.index, gender_counts.values, color=colors, edgecolor='white')
axes[1].set_title('Gender Distribution', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Gender')
axes[1].set_ylabel('Count')
for i, (val) in enumerate(gender_counts.values):
    axes[1].text(i, val + 5, str(val), ha='center', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.savefig('plot_age_gender.png', dpi=150, bbox_inches='tight')
plt.show()

# Treatment & Family History — % Labeled Bar Charts ---

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

for ax, col, color_pair, title in zip(
    axes,
    ['treatment', 'family_history'],
    [['#2ecc71', '#e74c3c'], ['#3498db', '#e67e22']],
    ['Sought Mental Health Treatment', 'Family History of Mental Illness']
):
    counts = df[col].value_counts()
    pcts   = (counts / counts.sum() * 100).round(1)
    bars   = ax.bar(counts.index, counts.values, color=color_pair, edgecolor='white', width=0.5)

    for bar, pct in zip(bars, pcts.values):
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 8,
                f'{pct}%', ha='center', va='bottom',
                fontsize=12, fontweight='bold')

    ax.set_title(title, fontsize=13, fontweight='bold')
    ax.set_xlabel(col.replace('_', ' ').title())
    ax.set_ylabel('Count')
    ax.set_ylim(0, counts.max() * 1.15)

plt.tight_layout()
plt.savefig('plot_treatment_familyhistory.png', dpi=150, bbox_inches='tight')
plt.show()

# Company Size & Work Interference Count Plots ---

fig, axes = plt.subplots(1, 2, figsize=(15, 5))

size_order = ['1-5', '6-25', '26-100', '100-500', '500-1000', 'More than 1000']

sns.countplot(data=df, x='no_employees', order=size_order,
              palette='Blues_d', ax=axes[0], edgecolor='white')
axes[0].set_title('Company Size Distribution', fontsize=13, fontweight='bold')
axes[0].set_xlabel('Number of Employees')
axes[0].set_ylabel('Count')
axes[0].tick_params(axis='x', rotation=20)

for p in axes[0].patches:
    axes[0].annotate(f'{int(p.get_height())}',
                     (p.get_x() + p.get_width() / 2, p.get_height() + 3),
                     ha='center', fontsize=9)

interfere_order = ['Never', 'Rarely', 'Sometimes', 'Often']

sns.countplot(data=df, x='work_interfere', order=interfere_order,
              palette='OrRd', ax=axes[1], edgecolor='white')
axes[1].set_title('Work Interference Due to Mental Health', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Frequency of Interference')
axes[1].set_ylabel('Count')

for p in axes[1].patches:
    axes[1].annotate(f'{int(p.get_height())}',
                     (p.get_x() + p.get_width() / 2, p.get_height() + 3),
                     ha='center', fontsize=9)

plt.tight_layout()
plt.savefig('plot_companysize_workinterfere.png', dpi=150, bbox_inches='tight')
plt.show()

# Remote Work, Tech Company & Self Employed — 3 Subplots ---

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

cols    = ['remote_work', 'tech_company', 'self_employed']
titles  = ['Remote Work', 'Tech Company', 'Self Employed']
palette = [['#1abc9c', '#e74c3c'], ['#2980b9', '#f39c12'], ['#8e44ad', '#27ae60']]

for ax, col, title, colors in zip(axes, cols, titles, palette):
    counts = df[col].value_counts()
    pcts   = (counts / counts.sum() * 100).round(1)
    bars   = ax.bar(counts.index, counts.values, color=colors,
                    edgecolor='white', width=0.45)

    for bar, pct, cnt in zip(bars, pcts.values, counts.values):
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 5,
                f'{cnt}\n({pct}%)', ha='center', va='bottom',
                fontsize=10, fontweight='bold')

    ax.set_title(title, fontsize=13, fontweight='bold')
    ax.set_xlabel(col.replace('_', ' ').title())
    ax.set_ylabel('Count')
    ax.set_ylim(0, counts.max() * 1.2)

plt.tight_layout()
plt.savefig('plot_remote_tech_selfemployed.png', dpi=150, bbox_inches='tight')
plt.show()

# Top 10 Countries by Respondent Count ---

top10 = df['Country'].value_counts().head(10).sort_values(ascending=True)

colors = ['#2c7bb6'] * len(top10)
colors[-1] = '#f0a500'

fig, ax = plt.subplots(figsize=(10, 6))

bars = ax.barh(top10.index, top10.values, color=colors, edgecolor='white', height=0.6)

for bar, val in zip(bars, top10.values):
    ax.text(bar.get_width() + 4, bar.get_y() + bar.get_height() / 2,
            str(val), va='center', fontsize=10, fontweight='bold')

ax.set_title('Top 10 Countries by Respondent Count', fontsize=14, fontweight='bold')
ax.set_xlabel('Number of Respondents')
ax.set_ylabel('Country')
ax.set_xlim(0, top10.max() * 1.12)
ax.spines[['top', 'right']].set_visible(False)

plt.tight_layout()
plt.savefig('plot_top10_countries.png', dpi=150, bbox_inches='tight')
plt.show()

"""# **Bivariate & Correlation Analysis.**"""

# Treatment vs Gender & Treatment vs Family History ---

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams['figure.dpi'] = 120

df = pd.read_csv('survey_cleaned.csv')

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

def grouped_pct_bar(ax, df, group_col, target_col, title, colors):
    ct = df.groupby([group_col, target_col]).size().unstack(fill_value=0)
    ct_pct = ct.div(ct.sum(axis=1), axis=0) * 100

    ct_pct.plot(kind='bar', ax=ax, color=colors, edgecolor='white',
                width=0.6, rot=0)

    for container in ax.containers:
        for bar in container:
            h = bar.get_height()
            if h > 1:
                ax.text(bar.get_x() + bar.get_width() / 2,
                        bar.get_height() + 0.8,
                        f'{h:.1f}%', ha='center', fontsize=9, fontweight='bold')

    ax.set_title(title, fontsize=13, fontweight='bold')
    ax.set_xlabel(group_col.replace('_', ' ').title())
    ax.set_ylabel('Percentage (%)')
    ax.set_ylim(0, 110)
    ax.legend(title=target_col.title(), loc='upper right')

grouped_pct_bar(axes[0], df, 'Gender',         'treatment',
                'Treatment Sought by Gender',          ['#2ecc71','#e74c3c'])
grouped_pct_bar(axes[1], df, 'family_history', 'treatment',
                'Treatment by Family History',         ['#3498db','#e67e22'])

plt.tight_layout()
plt.savefig('plot_treatment_gender_family.png', dpi=150, bbox_inches='tight')
plt.show()

# Treatment vs Work Interference & Company Size ---

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

interfere_order = ['Never', 'Rarely', 'Sometimes', 'Often']
size_order      = ['1-5', '6-25', '26-100', '100-500', '500-1000', 'More than 1000']

sns.countplot(data=df, x='work_interfere', hue='treatment',
              order=interfere_order, palette=['#2ecc71','#e74c3c'],
              ax=axes[0], edgecolor='white')
axes[0].set_title('Treatment by Work Interference Level', fontsize=13, fontweight='bold')
axes[0].set_xlabel('Work Interference Frequency')
axes[0].set_ylabel('Count')
axes[0].legend(title='Treatment')
axes[0].tick_params(axis='x', rotation=15)

for p in axes[0].patches:
    if p.get_height() > 0:
        axes[0].annotate(f'{int(p.get_height())}',
                         (p.get_x() + p.get_width() / 2, p.get_height() + 2),
                         ha='center', fontsize=8)

sns.countplot(data=df, x='no_employees', hue='treatment',
              order=size_order, palette=['#3498db','#e67e22'],
              ax=axes[1], edgecolor='white')
axes[1].set_title('Treatment by Company Size', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Number of Employees')
axes[1].set_ylabel('Count')
axes[1].legend(title='Treatment')
axes[1].tick_params(axis='x', rotation=20)

for p in axes[1].patches:
    if p.get_height() > 0:
        axes[1].annotate(f'{int(p.get_height())}',
                         (p.get_x() + p.get_width() / 2, p.get_height() + 2),
                         ha='center', fontsize=8)

plt.tight_layout()
plt.savefig('plot_treatment_interfere_size.png', dpi=150, bbox_inches='tight')
plt.show()

# Mental Health Consequence vs Benefits & Coworkers vs Supervisors ---

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

def grouped_count_pct_bar(ax, df, group_col, target_col, title, palette):
    ct     = df.groupby([group_col, target_col]).size().unstack(fill_value=0)
    ct_pct = ct.div(ct.sum(axis=1), axis=0) * 100

    ct_pct.plot(kind='bar', ax=ax, colormap=palette,
                edgecolor='white', width=0.65, rot=25)

    for container in ax.containers:
        for bar in container:
            h = bar.get_height()
            if h > 2:
                ax.text(bar.get_x() + bar.get_width() / 2,
                        bar.get_height() + 0.5,
                        f'{h:.1f}%', ha='center', va='bottom',
                        fontsize=8, fontweight='bold')

    ax.set_title(title, fontsize=13, fontweight='bold')
    ax.set_xlabel(group_col.replace('_', ' ').title())
    ax.set_ylabel('Percentage (%)')
    ax.set_ylim(0, 115)
    ax.legend(title=target_col.replace('_', ' ').title(),
              loc='upper right', fontsize=8)

grouped_count_pct_bar(axes[0], df,
                      'mental_health_consequence', 'benefits',
                      'MH Consequence Fear vs Employer Benefits',
                      'Set2')

grouped_count_pct_bar(axes[1], df,
                      'coworkers', 'supervisor',
                      'Comfort Discussing with Coworkers vs Supervisors',
                      'Set1')

plt.tight_layout()
plt.savefig('plot_stigma_support.png', dpi=150, bbox_inches='tight')
plt.show()

# Correlation Heatmap (Label-Encoded) with Treatment Highlight ---

from sklearn.preprocessing import LabelEncoder

df_enc = df.copy()

le = LabelEncoder()
for col in df_enc.select_dtypes(include='object').columns:
    df_enc[col] = le.fit_transform(df_enc[col].astype(str))

corr = df_enc.corr()

cols_sorted = ['treatment'] + [c for c in corr.columns if c != 'treatment']
corr = corr.loc[cols_sorted, cols_sorted]

fig, ax = plt.subplots(figsize=(16, 13))

mask = np.zeros_like(corr, dtype=bool)
mask[np.triu_indices_from(mask)] = True

sns.heatmap(corr, mask=mask, annot=True, fmt='.2f',
            cmap='RdBu_r', center=0, linewidths=0.4,
            linecolor='white', ax=ax,
            annot_kws={'size': 7},
            vmin=-1, vmax=1)

ax.add_patch(plt.Rectangle((0, 0),                   # x, y origin
                             len(cols_sorted),        # width
                             1,                       # height = 1 row
                             fill=False,
                             edgecolor='gold',
                             lw=3,
                             clip_on=False))

ax.set_title('Feature Correlation Heatmap\n(Gold box = treatment row)',
             fontsize=14, fontweight='bold')
ax.tick_params(axis='x', rotation=45, labelsize=9)
ax.tick_params(axis='y', rotation=0,  labelsize=9)

plt.tight_layout()
plt.savefig('plot_correlation_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

# Print top 10 features most correlated with treatment
print("=== Top 10 Features Correlated with Treatment ===")
print(corr['treatment'].drop('treatment').abs()
        .sort_values(ascending=False).head(10))

# Stacked Bar — Remote Work & Tech Company vs Treatment ---

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

def stacked_pct_bar(ax, df, group_col, target_col, title, colors):
    ct     = df.groupby([group_col, target_col]).size().unstack(fill_value=0)
    ct_pct = ct.div(ct.sum(axis=1), axis=0) * 100

    ct_pct.plot(kind='bar', stacked=True, ax=ax,
                color=colors, edgecolor='white', width=0.45, rot=0)

    for container in ax.containers:
        for bar in container:
            h = bar.get_height()
            y = bar.get_y() + h / 2          # vertical centre of segment
            if h > 4:                         # skip tiny slivers
                ax.text(bar.get_x() + bar.get_width() / 2,
                        y, f'{h:.1f}%',
                        ha='center', va='center',
                        fontsize=11, fontweight='bold', color='white')

    ax.set_title(title, fontsize=13, fontweight='bold')
    ax.set_xlabel(group_col.replace('_', ' ').title())
    ax.set_ylabel('Percentage (%)')
    ax.set_ylim(0, 110)
    ax.legend(title='Treatment', loc='upper right')

stacked_pct_bar(axes[0], df, 'remote_work',   'treatment',
                'Remote Work vs Treatment Sought',   ['#2ecc71','#e74c3c'])
stacked_pct_bar(axes[1], df, 'tech_company',  'treatment',
                'Tech Company vs Treatment Sought',  ['#3498db','#9b59b6'])

plt.tight_layout()
plt.savefig('plot_remote_tech_treatment.png', dpi=150, bbox_inches='tight')
plt.show()

"""# **Geographic Analysis.**"""

# Per-Country Statistics Table ---

import pandas as pd

df = pd.read_csv("survey_cleaned.csv")

df['treatment_bin'] = (df['treatment'] == 'Yes').astype(int)
df['family_history_bin'] = (df['family_history'] == 'Yes').astype(int)
df['mhc_bin'] = (df['mental_health_consequence'] == 'Yes').astype(int)
df['benefits_bin'] = (df['benefits'] == 'Yes').astype(int)

country_stats = df.groupby('Country').agg(
    total_respondents=('treatment_bin', 'count'),
    treatment_rate=('treatment_bin', 'mean'),
    family_history_rate=('family_history_bin', 'mean')
).reset_index()

country_stats = country_stats[country_stats['total_respondents'] >= 10].copy()

country_stats['treatment_rate_%'] = (country_stats['treatment_rate'] * 100).round(1)
country_stats['family_history_rate_%'] = (country_stats['family_history_rate'] * 100).round(1)

country_stats = country_stats.sort_values('treatment_rate_%', ascending=False).reset_index(drop=True)

display(country_stats[['Country', 'total_respondents', 'treatment_rate_%', 'family_history_rate_%']])

# Horizontal Bar Chart — Treatment Rate by Country ---

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np

top15_treat = country_stats.nlargest(15, 'treatment_rate_%').sort_values('treatment_rate_%')

norm = plt.Normalize(top15_treat['treatment_rate_%'].min(), top15_treat['treatment_rate_%'].max())
colors = cm.YlOrRd(norm(top15_treat['treatment_rate_%'].values))

fig, ax = plt.subplots(figsize=(11, 7))
bars = ax.barh(top15_treat['Country'], top15_treat['treatment_rate_%'], color=colors, edgecolor='white')

for bar, val in zip(bars, top15_treat['treatment_rate_%']):
    ax.text(val + 0.5, bar.get_y() + bar.get_height() / 2,
            f'{val}%', va='center', ha='left', fontsize=10, fontweight='bold')

ax.set_xlabel('Treatment-Seeking Rate (%)', fontsize=12)
ax.set_title('Treatment-Seeking Rate by Country (min. 10 respondents)', fontsize=14, fontweight='bold')
ax.set_xlim(0, top15_treat['treatment_rate_%'].max() + 10)
ax.spines[['top', 'right']].set_visible(False)
plt.tight_layout()
plt.show()

# Side-by-Side — Stigma vs Employer Support by Country ---

country_ext = df.groupby('Country').agg(
    total=('treatment_bin', 'count'),
    mhc_rate=('mhc_bin', 'mean'),
    benefits_rate=('benefits_bin', 'mean')
).reset_index()

country_ext = country_ext[country_ext['total'] >= 10].copy()
country_ext['mhc_%'] = (country_ext['mhc_rate'] * 100).round(1)
country_ext['benefits_%'] = (country_ext['benefits_rate'] * 100).round(1)

top_stigma   = country_ext.nlargest(15, 'mhc_%').sort_values('mhc_%')
top_benefits = country_ext.nlargest(15, 'benefits_%').sort_values('benefits_%')

fig, axes = plt.subplots(1, 2, figsize=(18, 7))

axes[0].barh(top_stigma['Country'], top_stigma['mhc_%'], color='#E05C5C', edgecolor='white')
for i, val in enumerate(top_stigma['mhc_%']):
    axes[0].text(val + 0.3, i, f'{val}%', va='center', fontsize=9)
axes[0].set_title('Top 15 Countries — Fear of Mental Health\nConsequences at Work (Yes%)', fontsize=12, fontweight='bold')
axes[0].set_xlabel('% Respondents Saying "Yes"')
axes[0].spines[['top', 'right']].set_visible(False)

axes[1].barh(top_benefits['Country'], top_benefits['benefits_%'], color='#4C9BE8', edgecolor='white')
for i, val in enumerate(top_benefits['benefits_%']):
    axes[1].text(val + 0.3, i, f'{val}%', va='center', fontsize=9)
axes[1].set_title('Top 15 Countries — Employer Provides\nMental Health Benefits (Yes%)', fontsize=12, fontweight='bold')
axes[1].set_xlabel('% Respondents Saying "Yes"')
axes[1].spines[['top', 'right']].set_visible(False)

plt.suptitle('Workplace Stigma vs Employer Support — Country Comparison', fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.show()

# US State Analysis — Respondent Count & Treatment Rate

us_df = df[(df['Country'] == 'United States') & (df['state'].notna())].copy()

state_stats = us_df.groupby('state').agg(
    count=('treatment_bin', 'count'),
    treatment_rate=('treatment_bin', 'mean')
).reset_index()

state_stats = state_stats[state_stats['count'] >= 5].copy()
state_stats['treatment_%'] = (state_stats['treatment_rate'] * 100).round(1)

top15_states = state_stats.nlargest(15, 'count').sort_values('count')
top15_states_treat = state_stats.nlargest(15, 'treatment_%').sort_values('treatment_%')

fig, axes = plt.subplots(1, 2, figsize=(18, 7))

axes[0].barh(top15_states['state'], top15_states['count'], color='#6A9EC2', edgecolor='white')
for i, val in enumerate(top15_states['count']):
    axes[0].text(val + 0.3, i, str(val), va='center', fontsize=9)
axes[0].set_title('Top 15 US States by Respondent Count', fontsize=13, fontweight='bold')
axes[0].set_xlabel('Number of Respondents')
axes[0].spines[['top', 'right']].set_visible(False)

axes[1].barh(top15_states_treat['state'], top15_states_treat['treatment_%'], color='#F4A261', edgecolor='white')
for i, val in enumerate(top15_states_treat['treatment_%']):
    axes[1].text(val + 0.3, i, f'{val}%', va='center', fontsize=9)
axes[1].set_title('Top 15 US States by Treatment-Seeking Rate\n(min. 5 respondents)', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Treatment Rate (%)')
axes[1].spines[['top', 'right']].set_visible(False)

plt.suptitle('US State-Level Mental Health Analysis', fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.show()

# Bubble Chart — Treatment Rate vs Stigma by Country ---

import matplotlib.pyplot as plt
import numpy as np

bubble_df = country_stats[['Country', 'total_respondents', 'treatment_rate_%']].merge(
    country_ext[['Country', 'mhc_%']], on='Country'
)

fig, ax = plt.subplots(figsize=(12, 8))

bubble_sizes = bubble_df['total_respondents'] * 3

scatter = ax.scatter(
    bubble_df['treatment_rate_%'],
    bubble_df['mhc_%'],
    s=bubble_sizes,
    alpha=0.65,
    c=bubble_df['treatment_rate_%'],
    cmap='coolwarm',
    edgecolors='white',
    linewidths=0.8
)

top10 = bubble_df.nlargest(10, 'total_respondents')
for _, row in top10.iterrows():
    ax.annotate(
        row['Country'],
        xy=(row['treatment_rate_%'], row['mhc_%']),
        xytext=(6, 4),
        textcoords='offset points',
        fontsize=9,
        fontweight='bold',
        color='#333333'
    )

cbar = plt.colorbar(scatter, ax=ax)
cbar.set_label('Treatment Rate (%)', fontsize=10)

ax.set_xlabel('Treatment-Seeking Rate (%)', fontsize=12)
ax.set_ylabel('Fear of Mental Health Consequences at Work (%)', fontsize=12)
ax.set_title('Treatment Rate vs Stigma by Country\n(Bubble size = Respondent Count)', fontsize=14, fontweight='bold')
ax.spines[['top', 'right']].set_visible(False)

plt.tight_layout()
plt.show()

"""# **Workplace Culture & Employer Policy Analysis**"""

# Employer Support vs Treatment — Benefits, Care Options, Wellness ---

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("survey_cleaned.csv")

treat_palette = {'Yes': '#4C9BE8', 'No': '#E8A24C'}
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

support_vars = [
    ('benefits',        'Employer Provides Mental Health Benefits'),
    ('care_options',    'Employer Offers Care Options'),
    ('wellness_program','Employer Has Wellness Program'),
]

for ax, (col, title) in zip(axes, support_vars):
    order = sorted(df[col].dropna().unique())
    sns.countplot(
        data=df, x=col, hue='treatment',
        order=order, hue_order=['Yes', 'No'],
        palette=treat_palette, edgecolor='white', ax=ax
    )
    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.set_xlabel('')
    ax.set_ylabel('Respondent Count' if ax == axes[0] else '')
    ax.tick_params(axis='x', labelsize=9)
    ax.legend(title='Sought Treatment', fontsize=9)
    ax.spines[['top', 'right']].set_visible(False)

plt.suptitle('Employer Support Policies vs Treatment-Seeking Behaviour',
             fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# Access & Safety Resources vs Treatment — Seek Help, Anonymity, Leave ---

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

access_vars = [
    ('seek_help', 'Employer Provides Seek-Help Resources'),
    ('anonymity', 'Anonymity Protected if Using Resources'),
    ('leave',     'Ease of Taking Mental Health Leave'),
]

leave_order = ['Very easy', 'Somewhat easy', "Don't know", 'Somewhat difficult', 'Very difficult']

for ax, (col, title) in zip(axes, access_vars):
    order = leave_order if col == 'leave' else sorted(df[col].dropna().unique())
    sns.countplot(
        data=df, x=col, hue='treatment',
        order=order, hue_order=['Yes', 'No'],
        palette=treat_palette, edgecolor='white', ax=ax
    )
    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.set_xlabel('')
    ax.set_ylabel('Respondent Count' if ax == axes[0] else '')
    ax.tick_params(axis='x', labelsize=8, rotation=15)
    ax.legend(title='Sought Treatment', fontsize=9)
    ax.spines[['top', 'right']].set_visible(False)

plt.suptitle('Workplace Access & Safety Policies vs Treatment-Seeking Behaviour',
             fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# Stigma & Openness vs Treatment — MH Consequence, Coworkers, Supervisor ---

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

stigma_vars = [
    ('mental_health_consequence', 'Fear of Neg. Consequence\nfor Disclosing MH Issue'),
    ('coworkers',                 'Comfortable Discussing MH\nwith Coworkers'),
    ('supervisor',                'Comfortable Discussing MH\nwith Supervisor'),
]

for ax, (col, title) in zip(axes, stigma_vars):
    order = sorted(df[col].dropna().unique())
    sns.countplot(
        data=df, x=col, hue='treatment',
        order=order, hue_order=['Yes', 'No'],
        palette=treat_palette, edgecolor='white', ax=ax
    )
    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.set_xlabel('')
    ax.set_ylabel('Respondent Count' if ax == axes[0] else '')
    ax.tick_params(axis='x', labelsize=9)
    ax.legend(title='Sought Treatment', fontsize=9)
    ax.spines[['top', 'right']].set_visible(False)

plt.suptitle('Workplace Stigma & Openness vs Treatment-Seeking Behaviour',
             fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# Heatmaps — Treatment Rate Across Policy Combinations ---

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

def treatment_heatmap(df, row_col, col_col, ax, title):
    pivot = df.groupby([row_col, col_col])['treatment'].apply(
        lambda x: round((x == 'Yes').mean() * 100, 1)
    ).unstack()
    sns.heatmap(
        pivot, annot=True, fmt='.1f', cmap='YlOrRd',
        linewidths=0.5, linecolor='white',
        cbar_kws={'label': 'Treatment Rate (%)'},
        ax=ax
    )
    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.set_xlabel(col_col.replace('_', ' ').title(), fontsize=10)
    ax.set_ylabel(row_col.replace('_', ' ').title(), fontsize=10)
    ax.tick_params(axis='x', rotation=15, labelsize=9)
    ax.tick_params(axis='y', rotation=0, labelsize=9)

treatment_heatmap(df, 'benefits', 'wellness_program', axes[0],
                  'Treatment Rate (%)\nBenefits × Wellness Program')

treatment_heatmap(df, 'seek_help', 'anonymity', axes[1],
                  'Treatment Rate (%)\nSeek-Help Resources × Anonymity')

plt.suptitle('Treatment Rate Across Employer Policy Combinations',
             fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# Interview Disclosure & MH vs Physical Priority — Split by Treatment ---

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

interview_order = sorted(df['mental_health_interview'].dropna().unique())
mvp_order       = sorted(df['mental_vs_physical'].dropna().unique())

sns.countplot(
    data=df, x='mental_health_interview', hue='treatment',
    order=interview_order, hue_order=['Yes', 'No'],
    palette=treat_palette, edgecolor='white', ax=axes[0]
)
axes[0].set_title('Willingness to Disclose MH Issue\nin a Job Interview', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Would Disclose in Interview')
axes[0].set_ylabel('Respondent Count')
axes[0].legend(title='Sought Treatment', fontsize=9)
axes[0].spines[['top', 'right']].set_visible(False)

sns.countplot(
    data=df, x='mental_vs_physical', hue='treatment',
    order=mvp_order, hue_order=['Yes', 'No'],
    palette=treat_palette, edgecolor='white', ax=axes[1]
)
axes[1].set_title('Employer Treats MH as Seriously\nas Physical Health', fontsize=12, fontweight='bold')
axes[1].set_xlabel('MH = Physical Health Priority')
axes[1].set_ylabel('')
axes[1].legend(title='Sought Treatment', fontsize=9)
axes[1].spines[['top', 'right']].set_visible(False)

plt.suptitle('Disclosure Attitudes & Perceived MH Parity — Split by Treatment',
             fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# --- Key Findings Summary ---
print("""
╔══════════════════════════════════════════════════════════════════════╗
║           STEP 5 — KEY FINDINGS: WORKPLACE CULTURE ANALYSIS          ║
╠══════════════════════════════════════════════════════════════════════╣
║                                                                      ║
║  1. EMPLOYER SUPPORT MATTERS: Respondents who reported that their    ║
║     employer provides mental health benefits or care options show    ║
║     consistently higher treatment-seeking rates — suggesting that    ║
║     visible policy support lowers the barrier to seeking help.       ║
║                                                                      ║
║  2. STIGMA SUPPRESSES HELP-SEEKING: Those who fear negative          ║
║     professional consequences for disclosing a mental health issue   ║
║     (mental_health_consequence = Yes) are less likely to have        ║
║     sought treatment — workplace stigma is a clear deterrent.        ║
║                                                                      ║
║  3. DISCLOSURE RELUCTANCE IS WIDESPREAD: The majority of             ║
║     respondents — regardless of treatment status — said they would   ║
║     NOT disclose a mental health issue in a job interview,           ║
║     reflecting persistent stigma around mental health in hiring.     ║
║                                                                      ║
╚══════════════════════════════════════════════════════════════════════╝
""")

"""# **Interactive Dashboard & Summary Report**"""

# Install & Build Figures — Correlations, Gender, Family History ---

import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv("survey_cleaned.csv")

# ── Encode target and clean Gender
df['treatment_bin'] = (df['treatment'] == 'Yes').astype(int)

# Normalise gender into 3 buckets
def norm_gender(g):
    g = str(g).strip().lower()
    if g in ['male', 'm', 'man', 'make', 'cis male', 'cis man', 'male (cis)']:
        return 'Male'
    elif g in ['female', 'f', 'woman', 'cis female', 'cis woman', 'female (cis)']:
        return 'Female'
    else:
        return 'Other'

df['gender_clean'] = df['Gender'].apply(norm_gender)

# ── Fig 1: Top 10 features correlated with treatment (point-biserial proxy) ─
encode_cols = ['family_history','work_interfere','no_employees','remote_work',
               'tech_company','benefits','care_options','wellness_program',
               'seek_help','anonymity','leave','mental_health_consequence',
               'phys_health_consequence','coworkers','supervisor',
               'mental_health_interview','phys_health_interview',
               'mental_vs_physical','obs_consequence','self_employed']

df_enc = df[encode_cols + ['treatment_bin']].apply(
    lambda col: pd.factorize(col)[0] if col.dtype == object else col
)

corr = df_enc.corr()['treatment_bin'].drop('treatment_bin').abs().sort_values(ascending=False)
top10 = corr.head(10).sort_values()

fig1 = go.Figure(go.Bar(
    x=top10.values, y=top10.index,
    orientation='h',
    marker=dict(color=top10.values, colorscale='Blues', showscale=False),
    text=[f'{v:.3f}' for v in top10.values], textposition='outside'
))
fig1.update_layout(
    title='Top 10 Features Correlated with Treatment-Seeking',
    xaxis_title='Absolute Correlation', yaxis_title='',
    plot_bgcolor='white', margin=dict(l=10, r=30, t=50, b=40), height=380
)

# ── Fig 2: Treatment rate by Gender
g_rate = df.groupby('gender_clean')['treatment_bin'].mean().reset_index()
g_rate.columns = ['Gender', 'rate']
g_rate['pct'] = (g_rate['rate'] * 100).round(1)

fig2 = go.Figure(go.Bar(
    x=g_rate['Gender'], y=g_rate['pct'],
    marker_color=['#4C9BE8','#E05C5C','#6AC47E'],
    text=[f'{v}%' for v in g_rate['pct']], textposition='outside'
))
fig2.update_layout(
    title='Treatment-Seeking Rate by Gender',
    yaxis_title='Treatment Rate (%)', xaxis_title='',
    plot_bgcolor='white', yaxis_range=[0, 100],
    margin=dict(l=10, r=10, t=50, b=40), height=380
)

# ── Fig 3: Treatment vs Family History (grouped bar)
fh = df.groupby(['family_history','treatment']).size().reset_index(name='count')
colors_fh = {'Yes': '#4C9BE8', 'No': '#E8A24C'}

fig3 = go.Figure()
for t in ['Yes', 'No']:
    sub = fh[fh['treatment'] == t]
    fig3.add_trace(go.Bar(
        name=f'Treatment: {t}', x=sub['family_history'], y=sub['count'],
        marker_color=colors_fh[t],
        text=sub['count'], textposition='outside'
    ))
fig3.update_layout(
    barmode='group',
    title='Treatment-Seeking vs Family History of Mental Illness',
    xaxis_title='Family History', yaxis_title='Respondent Count',
    plot_bgcolor='white', margin=dict(l=10, r=10, t=50, b=40), height=380,
    legend=dict(title='Sought Treatment')
)

print("Cell 1 complete — fig1, fig2, fig3 ready")

# Build Figures — Country Bar, Choropleth, Benefits × Treatment ---

# ── Per-country stats (min 10 respondents)
df['mhc_bin'] = (df['mental_health_consequence'] == 'Yes').astype(int)
country_stats = df.groupby('Country').agg(
    total=('treatment_bin', 'count'),
    treat_rate=('treatment_bin', 'mean')
).reset_index()
country_stats = country_stats[country_stats['total'] >= 10].copy()
country_stats['treat_pct'] = (country_stats['treat_rate'] * 100).round(1)
top15 = country_stats.nlargest(15, 'treat_pct').sort_values('treat_pct')

# ── Fig 4: Treatment rate by Country (horizontal bar, top 15)
fig4 = go.Figure(go.Bar(
    x=top15['treat_pct'], y=top15['Country'],
    orientation='h',
    marker=dict(color=top15['treat_pct'], colorscale='YlOrRd', showscale=True,
                colorbar=dict(title='Rate %')),
    text=[f'{v}%' for v in top15['treat_pct']], textposition='outside'
))
fig4.update_layout(
    title='Treatment-Seeking Rate by Country (Top 15, min. 10 respondents)',
    xaxis_title='Treatment Rate (%)', yaxis_title='',
    plot_bgcolor='white', margin=dict(l=10, r=60, t=50, b=40), height=420
)

# ── Fig 5: World Choropleth — treatment rate by country
# Map country names to ISO-3 codes using a manual dict for the common ones
iso3_map = {
    'United States': 'USA', 'United Kingdom': 'GBR', 'Canada': 'CAN',
    'Germany': 'DEU', 'Ireland': 'IRL', 'Netherlands': 'NLD',
    'Australia': 'AUS', 'France': 'FRA', 'India': 'IND',
    'New Zealand': 'NZL', 'Italy': 'ITA', 'Sweden': 'SWE',
    'Poland': 'POL', 'Switzerland': 'CHE', 'Belgium': 'BEL',
    'Brazil': 'BRA', 'South Africa': 'ZAF', 'Israel': 'ISR',
    'Bulgaria': 'BGR', 'Singapore': 'SGP', 'Finland': 'FIN',
    'Austria': 'AUT', 'Norway': 'NOR', 'Denmark': 'DNK',
    'Russia': 'RUS', 'Czech Republic': 'CZE', 'Romania': 'ROU',
    'Portugal': 'PRT', 'Spain': 'ESP', 'Mexico': 'MEX',
    'Nigeria': 'NGA', 'Greece': 'GRC', 'Hungary': 'HUN',
    'China': 'CHN', 'Japan': 'JPN', 'Croatia': 'HRV',
    'Thailand': 'THA', 'Philippines': 'PHL', 'Colombia': 'COL'
}
country_stats['iso3'] = country_stats['Country'].map(iso3_map)
choro_df = country_stats.dropna(subset=['iso3'])

fig5 = go.Figure(go.Choropleth(
    locations=choro_df['iso3'],
    z=choro_df['treat_pct'],
    text=choro_df['Country'],
    colorscale='YlOrRd',
    colorbar_title='Treatment %',
    marker_line_color='white',
    marker_line_width=0.5
))
fig5.update_layout(
    title='World Map — Treatment-Seeking Rate by Country',
    geo=dict(showframe=False, showcoastlines=True, projection_type='natural earth',
             bgcolor='#f9f9f9'),
    margin=dict(l=0, r=0, t=50, b=10), height=420
)

# ── Fig 6: Employer Benefits × Treatment (grouped bar)
ben = df.groupby(['benefits','treatment']).size().reset_index(name='count')
ben_order = ['Yes', "Don't know", 'No']

fig6 = go.Figure()
for t, col in [('Yes', '#4C9BE8'), ('No', '#E8A24C')]:
    sub = ben[ben['treatment'] == t].set_index('benefits').reindex(ben_order).reset_index()
    fig6.add_trace(go.Bar(
        name=f'Treatment: {t}', x=sub['benefits'], y=sub['count'],
        marker_color=col, text=sub['count'], textposition='outside'
    ))
fig6.update_layout(
    barmode='group',
    title='Mental Health Benefits Offered vs Treatment-Seeking',
    xaxis_title='Employer Provides Benefits', yaxis_title='Respondent Count',
    plot_bgcolor='white', margin=dict(l=10, r=10, t=50, b=40), height=380,
    legend=dict(title='Sought Treatment')
)

print("Cell 2 complete — fig4, fig5, fig6 ready")

# Work Interference, MH Consequence, & Random Forest Importances ---

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# ── Fig 7: Work Interference vs Treatment
wi_order = ['Never', 'Rarely', 'Sometimes', 'Often']
wi = df[df['work_interfere'].isin(wi_order)].groupby(
    ['work_interfere','treatment']).size().reset_index(name='count')

fig7 = go.Figure()
for t, col in [('Yes', '#4C9BE8'), ('No', '#E8A24C')]:
    sub = wi[wi['treatment'] == t].set_index('work_interfere').reindex(wi_order).reset_index()
    fig7.add_trace(go.Bar(
        name=f'Treatment: {t}', x=sub['work_interfere'], y=sub['count'],
        marker_color=col, text=sub['count'], textposition='outside'
    ))
fig7.update_layout(
    barmode='group',
    title='Work Interference Level vs Treatment-Seeking',
    xaxis_title='Work Interference (Self-Reported)', yaxis_title='Respondent Count',
    plot_bgcolor='white', margin=dict(l=10, r=10, t=50, b=40), height=380,
    legend=dict(title='Sought Treatment')
)

# ── Fig 8: Mental Health Consequence Fear vs Treatment
mhc_order = ['No', 'Maybe', 'Yes']
mhc = df.groupby(['mental_health_consequence','treatment']).size().reset_index(name='count')

fig8 = go.Figure()
for t, col in [('Yes', '#4C9BE8'), ('No', '#E8A24C')]:
    sub = mhc[mhc['treatment'] == t].set_index(
        'mental_health_consequence').reindex(mhc_order).reset_index()
    fig8.add_trace(go.Bar(
        name=f'Treatment: {t}', x=sub['mental_health_consequence'], y=sub['count'],
        marker_color=col, text=sub['count'], textposition='outside'
    ))
fig8.update_layout(
    barmode='group',
    title='Fear of Negative Consequence for MH Disclosure vs Treatment',
    xaxis_title='Fear of Negative Consequence', yaxis_title='Respondent Count',
    plot_bgcolor='white', margin=dict(l=10, r=10, t=50, b=40), height=380,
    legend=dict(title='Sought Treatment')
)

# ── Random Forest + Fig 9: Feature Importances
encode_cols = ['family_history','work_interfere','no_employees','remote_work',
               'tech_company','benefits','care_options','wellness_program',
               'seek_help','anonymity','leave','mental_health_consequence',
               'phys_health_consequence','coworkers','supervisor',
               'mental_health_interview','phys_health_interview',
               'mental_vs_physical','obs_consequence','self_employed']

df_enc = df[encode_cols + ['treatment_bin']].apply(
    lambda col: pd.factorize(col)[0] if col.dtype == object else col
)
df_enc = df_enc.dropna()

X = df_enc[encode_cols]
y = df_enc['treatment_bin']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf = RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)
rf.fit(X_train, y_train)
acc = rf.score(X_test, y_test)
print(f"  RF Accuracy: {acc:.3f}")

importances = pd.Series(rf.feature_importances_, index=encode_cols)
top12 = importances.nlargest(12).sort_values()
top_predictor = importances.idxmax()
fig9 = go.Figure(go.Bar(
    x=top12.values, y=top12.index,
    orientation='h',
    marker=dict(color=top12.values, colorscale='Teal', showscale=False),
    text=[f'{v:.3f}' for v in top12.values], textposition='outside'
))
fig9.update_layout(
    title=f'Top 12 Feature Importances — Random Forest (Accuracy: {acc:.1%})',
    xaxis_title='Importance Score', yaxis_title='',
    plot_bgcolor='white', margin=dict(l=10, r=30, t=50, b=40), height=420
)

print(f"Cell 3 complete — fig7, fig8, fig9 ready | Top predictor: {top_predictor}")

# Assemble & Export Full HTML Dashboard ---

import plotly.io as pio

# ── Key stats for the header cards
total_resp   = len(df)
treat_rate   = f"{df['treatment_bin'].mean() * 100:.1f}%"
top_pred_fmt = top_predictor.replace('_', ' ').title()

# ── Convert all figures to HTML div strings
cfg = dict(responsive=True)
def fig_html(fig):
    return pio.to_html(fig, full_html=False, include_plotlyjs=False, config=cfg)

divs = [fig_html(f) for f in [fig1, fig2, fig3, fig4, fig5, fig6, fig7, fig8, fig9]]

# ── Build the full dashboard HTML
html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Mental Health in Tech — EDA Dashboard</title>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: 'Segoe UI', Arial, sans-serif;
      background: #f0f2f5;
      color: #222;
    }}

    /* ── Header ── */
    .header {{
      background: linear-gradient(135deg, #1a237e 0%, #1565c0 60%, #0288d1 100%);
      color: white;
      padding: 36px 48px 28px;
    }}
    .header h1 {{ font-size: 2rem; font-weight: 700; letter-spacing: 0.5px; }}
    .header p  {{ margin-top: 6px; font-size: 0.95rem; opacity: 0.85; }}

    /* ── Stat Cards ── */
    .cards {{
      display: flex; gap: 20px; flex-wrap: wrap;
      padding: 28px 48px 8px;
    }}
    .card {{
      flex: 1; min-width: 200px;
      background: white;
      border-radius: 12px;
      padding: 22px 28px;
      box-shadow: 0 2px 12px rgba(0,0,0,0.08);
      border-left: 5px solid;
    }}
    .card:nth-child(1) {{ border-color: #1565c0; }}
    .card:nth-child(2) {{ border-color: #00897b; }}
    .card:nth-child(3) {{ border-color: #e53935; }}
    .card-label {{ font-size: 0.78rem; font-weight: 600;
                   text-transform: uppercase; letter-spacing: 1px;
                   color: #888; margin-bottom: 6px; }}
    .card-value {{ font-size: 2rem; font-weight: 700; color: #1a237e; }}
    .card-sub   {{ font-size: 0.8rem; color: #aaa; margin-top: 4px; }}

    /* ── Section Labels ── */
    .section-title {{
      padding: 28px 48px 4px;
      font-size: 1.1rem; font-weight: 700;
      color: #1a237e; letter-spacing: 0.3px;
    }}

    /* ── Chart Grid ── */
    .grid {{
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 20px;
      padding: 16px 48px;
    }}
    .chart-card {{
      background: white;
      border-radius: 12px;
      padding: 16px;
      box-shadow: 0 2px 12px rgba(0,0,0,0.07);
      overflow: hidden;
    }}
    .chart-card.full {{
      grid-column: 1 / -1;   /* spans both columns */
    }}

    /* ── Key Findings ── */
    .findings {{
      margin: 24px 48px 40px;
      background: white;
      border-radius: 12px;
      padding: 28px 36px;
      box-shadow: 0 2px 12px rgba(0,0,0,0.07);
    }}
    .findings h2 {{
      font-size: 1.15rem; font-weight: 700;
      color: #1a237e; margin-bottom: 18px;
      padding-bottom: 10px;
      border-bottom: 2px solid #e8eaf6;
    }}
    .findings ul {{ list-style: none; display: flex; flex-direction: column; gap: 12px; }}
    .findings li {{
      display: flex; align-items: flex-start; gap: 12px;
      font-size: 0.93rem; line-height: 1.6; color: #333;
    }}
    .findings li::before {{
      content: '▶';
      color: #1565c0; font-size: 0.7rem;
      margin-top: 4px; flex-shrink: 0;
    }}
    .findings li strong {{ color: #1a237e; }}

    /* ── Footer ── */
    .footer {{
      text-align: center; padding: 20px;
      font-size: 0.78rem; color: #bbb;
      border-top: 1px solid #e0e0e0;
    }}

    @media (max-width: 900px) {{
      .grid {{ grid-template-columns: 1fr; }}
      .chart-card.full {{ grid-column: 1; }}
      .cards, .grid, .findings, .section-title {{ padding-left: 20px; padding-right: 20px; }}
      .header {{ padding: 24px 20px; }}
    }}
  </style>
</head>
<body>

<!-- ══ HEADER ══ -->
<div class="header">
  <h1>Mental Health in Tech — EDA Dashboard</h1>
  <p>Open Mental Health Survey 2014 &nbsp;|&nbsp; Exploratory Data Analysis &nbsp;|&nbsp;
     Python · Pandas · Plotly · Scikit-Learn</p>
</div>

<!-- ══ STAT CARDS ══ -->
<div class="cards">
  <div class="card">
    <div class="card-label">Total Respondents</div>
    <div class="card-value">{total_resp:,}</div>
    <div class="card-sub">Tech industry professionals worldwide</div>
  </div>
  <div class="card">
    <div class="card-label">Treatment-Seeking Rate</div>
    <div class="card-value">{treat_rate}</div>
    <div class="card-sub">Of surveyed respondents sought treatment</div>
  </div>
  <div class="card">
    <div class="card-label">Top Predictor (RF)</div>
    <div class="card-value" style="font-size:1.25rem">{top_pred_fmt}</div>
    <div class="card-sub">Highest importance — Random Forest model</div>
  </div>
</div>

<!-- ══ SECTION 1: Individual & Demographic Factors ══ -->
<div class="section-title">Individual &amp; Demographic Factors</div>
<div class="grid">
  <div class="chart-card">{divs[0]}</div>
  <div class="chart-card">{divs[1]}</div>
  <div class="chart-card">{divs[2]}</div>
  <div class="chart-card">{divs[7]}</div>
</div>

<!-- ══ SECTION 2: Geographic Analysis ══ -->
<div class="section-title">Geographic Analysis</div>
<div class="grid">
  <div class="chart-card">{divs[3]}</div>
  <div class="chart-card full">{divs[4]}</div>
</div>

<!-- ══ SECTION 3: Workplace Culture & Employer Policy ══ -->
<div class="section-title">Workplace Culture &amp; Employer Policy</div>
<div class="grid">
  <div class="chart-card">{divs[5]}</div>
  <div class="chart-card">{divs[6]}</div>
</div>

<!-- ══ SECTION 4: Predictive Model ══ -->
<div class="section-title">Predictive Model — Random Forest Feature Importances</div>
<div class="grid">
  <div class="chart-card full">{divs[8]}</div>
</div>

<!-- ══ KEY FINDINGS ══ -->
<div class="findings">
  <h2> Key Findings</h2>
  <ul>
    <li><strong>Treatment-seeking is near-even:</strong> ~50.6% of respondents have sought treatment,
        indicating significant mental health burden across the tech industry.</li>
    <li><strong>Family history is the strongest predictor:</strong> Respondents with a family history
        of mental illness seek treatment at markedly higher rates — the top feature in both
        correlation and Random Forest analyses.</li>
    <li><strong>Work interference drives help-seeking:</strong> Those reporting that mental health
        issues "Often" interfere with work are far more likely to have sought treatment,
        suggesting crisis-point motivation rather than proactive care.</li>
    <li><strong>Employer benefits matter:</strong> Respondents at companies offering explicit mental
        health benefits show higher treatment rates — visible policy support lowers barriers
        to help-seeking.</li>
    <li><strong>Stigma suppresses disclosure:</strong> Fear of negative professional consequences
        for disclosing a mental health issue is prevalent and correlates with avoidance of
        treatment — workplace culture is a critical intervention point.</li>
    <li><strong>Geography reveals disparities:</strong> The US and Ireland lead in treatment-seeking
        rates; the choropleth highlights that access and cultural norms vary significantly
        across countries, pointing to systemic differences in mental healthcare adoption.</li>
  </ul>
</div>

<div class="footer">
  Mental Health in Tech EDA · Open Mental Health Survey 2014 ·
  Built with Python, Pandas, Plotly &amp; Scikit-Learn
</div>

</body>
</html>"""

# ── Save to file ─────────────────────────────────────────────────────────────
output_path = "mental_health_dashboard.html"
with open(output_path, "w", encoding="utf-8") as f:
    f.write(html)

print(f"Dashboard saved: {output_path}")

# --- Cell 5: Download Dashboard & Confirm Export ---

import os

size_bytes = os.path.getsize("mental_health_dashboard.html")
size_kb    = size_bytes / 1024

print(f"  File size : {size_kb:,.1f} KB")
print(f"  Location  : mental_health_dashboard.html")
print()
print("=" * 62)
print("  Dashboard exported successfully —")
print("  open mental_health_dashboard.html in your browser")
print("=" * 62)

try:
    from google.colab import files
    files.download("mental_health_dashboard.html")
    print("\n  ⬇  Download triggered via google.colab.files")
except ImportError:
    print("\n  ℹ  Not running in Colab.")
    print(f"     Find your dashboard at: {os.path.abspath('mental_health_dashboard.html')}")